Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -121,6 +121,27 @@ bpwatch start restore_cache
   done
 bpwatch stop restore_cache
 
+# Before we get into python, we need ODBC
+echo "-----> Installing unixODBC"
+
+S3BUCKET="https://s3.amazonaws.com/chameleon-heroku-assets"
+UNIX_ODBC_WITH_HANA_TGZ="$S3BUCKET/unixodbc.tar.gz"
+UNIX_ODBC_DIR="$0/vendor/unixodbc"
+
+echo "----->" $0
+echo "----->" $UNIX_ODBC_DIR
+echo "----->" $UNIX_ODBC_WITH_HANA_TGZ
+
+mkdir -p $UNIX_ODBC_DIR
+curl $UNIX_ODBC_WITH_HANA_TGZ -s -o - | tar -xz -C $UNIX_ODBC_DIR -f - 
+
+if [[ $? != 0 ]] ; then
+    echo "-----> ERROR!"
+fi
+
+
+
+
 set +e
 # Create set-aside `.heroku` folder.
 mkdir .heroku &> /dev/null
@@ -130,6 +151,7 @@ mkdir -p $(dirname $PROFILE_PATH)
 
 set +e
 PYTHON_VERSION=$(cat runtime.txt)
+
 
 # Install Python.
 if [ -f .heroku/python-version ]; then
@@ -164,6 +186,7 @@ if [ ! "$SKIP_INSTALL" ]; then
 else
   puts-step "Using Python runtime ($PYTHON_VERSION)"
 fi
+
 
 # If Pip isn't up to date:
 if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_VERSION* ]]; then
